baseURL: https://sonalimohnani.netlify.app
languageCode: en-us
title: Sonali Mohnani
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Join me!
    subtitle: |-
      In this website you will find my self-development journey as I learn & introspect about life.
    title: Hi, my name is Sonali
  blog: {}
  contact:
    address:
      - city: New York, NY 10011
        country: United States
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: sonalimohnani99@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (732) 666-7768
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: no
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-file
        label: Resume
        url: /files/Resume.pdf
      - icon: fa-at
        label: Email
        url: mailto:sonalimohnani99@gmail.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/sonali-mohnani-560b90140/
      - icon: fa-github
        label: GitHub
        url: https://github.com/sonalimohnani99
      - icon: fa-whatsapp
        label: Whatsapp
        url: https://wa.me/+17326667768
      - icon: fa-instagram
        label: Instagram
        url: https://Instagram.com/sonalimohnani
  image: ''
  name: Sonali Mohnani
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle:
    title: Sonali Mohnani
  tiles:
    enable: yes
    showcase:
      - image: about-me.jpg
        subtitle: Learn more about me
        title: About Me
        url: blogs/tempus
      - image: fearless-girl.jpg
        subtitle: My professional journey
        title: CV
        url: /files/Resume.pdf
      - image: mini-me.jpg
        subtitle: Passing on some tenets I hope they live by
        title: Letter to My Future Kids
        url: blogs/aliquam
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: About Me
    enable: yes
    title: "Learn a bit about me"
    subtitle: "A first-generation student born and raised in Chile.
      \n Graduate of the Stern School of Business at NYU, having studied Finance and 
      Computing & Data Science and currently pursuing a Master's in Financial Analysis 
      at the London Business School. \n Exploring the world and passionate about learning!"
    url: blogs
