baseURL: https://smohnani.netlify.app
languageCode: en-us
title: Sonali Mohnani
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Join me!
    subtitle: |-
      In this website you will find my self-development journey as I learn & introspect about life.
    title: Hi, my name is Sonali
  blog: {}
  contact:
    address:
      - city: New York, NY 10011
        country: United States
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: sonalimohnani99@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (732) 666-7768
        title: Phone
  custom_css: []
  custom_js: []
  description: Sonali Mohnani's Website
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    enable: yes
    social:
      - icon: fa-file
        label: Resume
        url: /files/Resume.pdf
      - icon: fa-at
        label: Email
        url: mailto:sonalimohnani99@gmail.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/sonali-mohnani-560b90140/
      - icon: fa-github
        label: GitHub
        url: https://github.com/sonalimohnani99
      - icon: fa-whatsapp
        label: Whatsapp
        url: https://wa.me/+17326667768
      - icon: fa-instagram
        label: Instagram
        url: https://Instagram.com/sonalimohnani
  image: ''
  name: Sonali Mohnani
  navigation:
    links:
      - name: Home
        url: '#'
      - name: About
        url: blogs
      - name: Projects
        url: projects
    menu: Menu
    subtitle:
    title: Sonali Mohnani
  tiles:
    enable: yes
    showcase:
      - image: about-me.jpg
        subtitle: Learn more about me
        title: About Me
        url: blogs/about
      - image: fearless-girl.jpg
        subtitle: My professional journey
        title: CV
        url: /files/Resume.pdf
      - image: undo.jpg
        subtitle: Living in the shadows
        title: My Undocumented Journey
        url: blogs/undocumented
      - image: mini-me.jpg
        subtitle: Passing on some tenets I hope they live by
        title: Letter to My Future Kids
        url: blogs/Kids
      - image: cook.jpg
        subtitle: My mom cooks some bomb food and I'm a college student. This recipe book has been a life savior. 
        title: Mom's Cooking
        url: /files/recipes.pdf
      - image: thirteenth.jpeg
        subtitle: Letter to the Corrections Corporations of America
        title: The Thirteenth Amendment- A Loophole for Slavery
        url: /files/Ccorp.pdf
  two:
    buttonText: Portfolio
    enable: yes
    title: "My R Projects"
    subtitle: I have been learning how to code at London Business School. Check out some of my work! 
    url: Projects